apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: core-work-management-frontend-image
    newName: ghcr.io/eed-web-application/core-work-management-frontend:sha-2b628c1